### ISSUE TITLE
Heroku Server

### ISSUE THREAD

**Issue by NoPenguinsLand** [gfontenot/daily-journal#2]
Not sure if you're using free version but Heroku will no longer offer free server starting on November 28, 2022.

I've been using your website regularly so hope it'll continue to exist :)

**Comment by gfontenot** [comment]
Hey, thanks for the reminder! I knew that Heroku was going to change but I've been lazy about moving somewhere else because I was 100% positive that I was the only person using this thing. I'm _thrilled_ to hear that you've been getting use out of it as well! I'll prioritize figuring out what I need to do to keep it up and running so that it doesn't get interrupted.

**Comment by NoPenguinsLand** [comment]
👍 Your website was recommended on [r/journaling](https://www.reddit.com/r/Journaling/), which is how I came across your website and which also means that a handful of other people are using it.

**Comment by gfontenot** [comment]
Ha, that's wild. Thanks for letting me know!

**Comment by gfontenot** [comment]
This should be updated to use eco dynos now, so it should stick around for at least another 5 years till they EOL the stack I just moved to! Thanks for the push on this!

**Comment by NoPenguinsLand** [comment]
Thanks Gordon!
